name: Unstructured Data Pipeline

on:
  push:
    branches: [ main ]
    paths: [ 'src/unstructured_data_pipeline/**' ]

jobs:
  snowflake-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Clear existing unstructured data on snowflake
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

        run: uv run -m src.clear_unstructured_data.py

      - name: Send unstructured data to snowflake
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

        run: uv run -m src.unstructured_data_pipeline.main